name: test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.x]
        include:
          - os: ubuntu-latest
            python-version: 3.7
          - os: ubuntu-latest
            python-version: pypy3.9
      fail-fast: false
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - uses: Gr1N/setup-poetry@v8
    - run: poetry install
    - run: poetry run pytest
    - uses: codecov/codecov-action@v3
      if: ${{ matrix.os == 'ubuntu-latest' && matrix.python-version == '3.x' }}